### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by FQQD** [N1lzh/Discord-Guess-Member-Bot#1]
Hey there, this is a great Discord Bot, but I think you should add a leaderboard, so the people try to compete with each other.
You could make it so you can disable and enable it in the config.json.
With the /leaderboard command it would show a list of the top 10 people on the server, who guessed the most Persons.
With /rank you could see how far you've come, so how many people you've already guessed and wich rank you are.

Greetings, FQQD

**Comment by N1lzh** [comment]
Hi FQQD,
sounds great! I will try my best on implementing it into the bot, you will hear from me as soon as I'm done.

**Comment by N1lzh** [comment]
The update is now on github!
