### ISSUE TITLE
Perfect Bot Cheers!

### ISSUE THREAD

**Issue by Saizuo** [N1lzh/Discord-Guess-Member-Bot#3]
I wanna ask for permission if I can make a video on the source code? Its really a creative Bot! 

My Channel - https://www.youtube.com/channel/UC61eXKDPxuQot7ojsijLPMg

**Comment by N1lzh** [comment]
Feel free to make a video about the bot as long as you link the github repository. 
I will look forward to see your Video!

**Comment by N1lzh** [comment]
I will close this Issue now. Feel free to reopen and post the link of the video here once it is released.
edit: grammar
